version: '3'
services:
  postgres:
    image: shold046/postgres-11-rus
    environment:
      POSTGRES_DB: theboatscom
      POSTGRES_USER: theboatscom
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ../asstets/dump:/tmp